/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;

namespace SKS.ParcelLogistics.WebService.DTOs
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse200 :  IEquatable<InlineResponse200>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse200" /> class.
        /// </summary>
        /// <param name="TrackingId">The tracking ID of the parcel..</param>
        public InlineResponse200(string TrackingId = default(string))
        {
            this.TrackingId = TrackingId;
            
        }

        /// <summary>
        /// The tracking ID of the parcel.
        /// </summary>
        /// <value>The tracking ID of the parcel.</value>
        [DataMember(Name="trackingId")]
        public string TrackingId { get; set; }

       

        /// <summary>
        /// Returns true if InlineResponse200 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse200 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse200 other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.TrackingId == other.TrackingId ||
                    this.TrackingId != null &&
                    this.TrackingId.Equals(other.TrackingId)
                );
        }
    }
}
