/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SKS.ParcelLogistics.WebService.DTOs
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Warehouse : IEquatable<Warehouse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Warehouse" /> class.
        /// </summary>
        /// <param name="Code">Code (required).</param>
        /// <param name="Description">Description (required).</param>
        /// <param name="Duration">Duration (required).</param>
        /// <param name="NextHops">NextHops.</param>
        /// <param name="Trucks">Trucks.</param>
        public Warehouse(string Code = default(string), string Description = default(string), decimal? Duration = default(decimal?), List<Warehouse> NextHops = default(List<Warehouse>), List<Truck> Trucks = default(List<Truck>))
        {
            this.Code = Code;
            this.Description = Description;
            this.Duration = Duration;
            this.NextHops = NextHops;
            this.Trucks = Trucks;
        }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code")]
        public string Code { get; set; }
        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description")]
        public string Description { get; set; }
        /// <summary>
        /// Gets or Sets Duration
        /// </summary>
        [DataMember(Name = "duration")]
        public decimal? Duration { get; set; }
        /// <summary>
        /// Gets or Sets NextHops
        /// </summary>
        [DataMember(Name = "nextHops")]
        public List<Warehouse> NextHops { get; set; }
        /// <summary>
        /// Gets or Sets Trucks
        /// </summary>
        [DataMember(Name = "trucks")]
        public List<Truck> Trucks { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if Warehouse instances are equal
        /// </summary>
        /// <param name="other">Instance of Warehouse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Warehouse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    this.Code == other.Code ||
                    this.Code != null &&
                    this.Code.Equals(other.Code)
                ) &&
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) &&
                (
                    this.Duration == other.Duration ||
                    this.Duration != null &&
                    this.Duration.Equals(other.Duration)
                ) &&
                (
                    this.NextHops == other.NextHops ||
                    this.NextHops != null &&
                    this.NextHops.SequenceEqual(other.NextHops)
                ) &&
                (
                    this.Trucks == other.Trucks ||
                    this.Trucks != null &&
                    this.Trucks.SequenceEqual(other.Trucks)
                );
        }
    }
}